[0m19:11:17.171313 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000273D55D4EC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000273D374CA50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000273D6202350>]}


============================== 19:11:17.209019 | 0afa91a8-b55b-466a-b0d4-d05a781af369 ==============================
[0m19:11:17.209019 [info ] [MainThread]: Running with dbt=1.9.2
[0m19:11:17.212894 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\HP 830 G6\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init my_project', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:11:17.304051 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'WindowsPath'.. Dictionary: {'dir': WindowsPath('C:/Users/HP 830 G6/.dbt')}
[0m19:11:17.305763 [info ] [MainThread]: Creating dbt configuration folder at 
[0m19:11:17.313025 [debug] [MainThread]: Starter project path: C:\Users\HP 830 G6\desktop\KAIM\week-7\dbt-env\Lib\site-packages\dbt\include\starter_project
[0m19:11:17.389269 [info ] [MainThread]: 
Your new dbt project "my_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m19:11:17.390999 [info ] [MainThread]: Setting up your profile.
[0m19:11:46.454847 [error] [MainThread]: Encountered an error:
list index out of range
[0m19:11:46.461686 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\HP 830 G6\desktop\KAIM\week-7\dbt-env\Lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\HP 830 G6\desktop\KAIM\week-7\dbt-env\Lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\HP 830 G6\desktop\KAIM\week-7\dbt-env\Lib\site-packages\dbt\cli\main.py", line 477, in init
    results = task.run()
  File "C:\Users\HP 830 G6\desktop\KAIM\week-7\dbt-env\Lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\HP 830 G6\desktop\KAIM\week-7\dbt-env\Lib\site-packages\dbt\task\init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "C:\Users\HP 830 G6\desktop\KAIM\week-7\dbt-env\Lib\site-packages\dbt\task\init.py", line 243, in ask_for_adapter_choice
    return available_adapters[numeric_choice - 1]
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

[0m19:11:46.464542 [debug] [MainThread]: Command `dbt init` failed at 19:11:46.464216 after 29.70 seconds
[0m19:11:46.465450 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000273D6729E00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000273D6769250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000273D657ECF0>]}
[0m19:11:46.466253 [debug] [MainThread]: Flushing usage events
[0m19:11:47.395083 [debug] [MainThread]: An error was encountered while trying to flush usage events
